version: "3.8"

services:
  gandalf:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - database
    restart: always

  database:
    image: mongo
    command: mongod --replSet rs
    volumes:
      - .data/mongodb:/data/db
    ports:
      - 27017:27017
    restart: always
